### ISSUE TITLE
[Feature Request] An example using both cores of the rp2040

### ISSUE THREAD

**Issue by pepeRossRobotics** [107-systems/OpenCyphalPicoBase-firmware#43]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### ⚡ Feature Request
Maybe there is already an example somewhere, but I haven't found it.
It would be really useful to have an example using both cores of the rp2040, one that is in charge of just handling the mcp2515 and the Cyphal Spin. 

I toyed with the idea earlier today, but wasn't able to make something that does not crash the uC and needs a watchdog reboot.

I was using `rp2040.idleOtherCore()` and `rp2040.resumeOtherCore()` in different places.

Thoughts?

**Comment by aentinger** [comment]
Hi ☕ 👋 

While interesting in theory I dont want to make the examples too core-specific. Eventually there'll be support for C++14 again and that would open up too all ArduinoCore-mbed or arduino-esp supported boards.

Also ArduinoCore-renesas boards are already supported and those have onboard CAN without external transceiver such as the MCP2515.
